services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
        PAYLOAD_PUBLIC_SERVER_URL: ${PAYLOAD_PUBLIC_SERVER_URL}
    container_name: nic-electrik-payload-staging
    env_file:
      - .env.staging
    ports:
      - '3000:3000'
    restart: unless-stopped
