services:
  app:
    image: ${APP_IMAGE}
    pull_policy: always
    container_name: nic-electrik-payload-staging
    env_file:
      - .env.staging
    ports:
      - '3000:3000'
    restart: unless-stopped
